version: '3.1'

services:

  schedules-mongo:
    image: mongo:4.2.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: schedule
      MONGO_INITDB_ROOT_PASSWORD: schedule
    ports:
      - "27017:27017"

  schedules-svc:
    image: schedules-svc
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - schedules-mongo
    environment:
      WAIT_HOSTS: schedules-mongo:27017
      mongo.url: mongodb://schedule:schedule@schedules-mongo:27017